language: python
python:
  - "3.5"
sudo: required

services:
  - docker

before_install:
  - docker build -t davidshen84/scikit-learn
  - docker run -d -p 127.0.0.1:80:4567 davidshen84/scikit-learn /bin/sh -c "cd /root/scikit-learn; bundle exec foreman start;"
  - docker ps -a
  - docker run davidshen84/scikit-learn


notifications:
  email: false
# command to run tests
script: python3 test.py
