language: python
python:
  - "3.5"
# before_install:
#   - sudo apt-get install libblas-dev
#   - sudo apt-get install liblapack-dev
#   - sudo apt-get install gfortran
install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo pip install enum34
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pip numpy pandas requests nose numpydoc sphinx'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  # install your own package into the environment
  # - python setup.py install

notifications:
  email: false
# command to run tests
script: python3 test.py
