language: python
python:
  - "3.5"
sudo: required

services:
  - docker

before_install:
  - docker build -t mxhao2/helloTravis
  - docker run -d -p 127.0.0.1:80:4567 mxhao2/helloTravis /bin/sh -c "cd /root/helloTravis; bundle exec foreman start;"
  - docker ps -a
  - docker run mxhao2/helloTravis /bin/sh -c "cd /root/helloTravis; bundle exec rake test"


notifications:
  email: false
# command to run tests
script: python3 test.py
