language: python
python:
  - "3.5"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev

before_install:
 - sudo apt-get install -qq python-numpy python-scipy

install:
  python3 setup.py develop

# command to run tests
script: python3 test.py
